apiVersion: v1
kind: Service
metadata:
  labels:
    app: atlas
  name: atlas
  namespace: default
spec:
  ports:
  - port: 21000
    protocol: TCP
    targetPort: 21000
  selector:
    app: atlas
  type: LoadBalancer

